// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Courses__CheckIsCompanyController from "./courses/check_is_company_controller"
application.register("courses--check-is-company", Courses__CheckIsCompanyController)

import Courses__SelectCompanyController from "./courses/select_company_controller"
application.register("courses--select-company", Courses__SelectCompanyController)

import Courses__SelectCourseTypeController from "./courses/select_course_type_controller"
application.register("courses--select-course-type", Courses__SelectCourseTypeController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import TselectController from "./tselect_controller"
application.register("tselect", TselectController)
