// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)

import Courses__CheckIsCompanyController from "./courses/check_is_company_controller"
application.register("courses--check-is-company", Courses__CheckIsCompanyController)

import Courses__FormController from "./courses/form_controller"
application.register("courses--form", Courses__FormController)

import Courses__SelectCompanyController from "./courses/select_company_controller"
application.register("courses--select-company", Courses__SelectCompanyController)

import Courses__SelectCourseTypeController from "./courses/select_course_type_controller"
application.register("courses--select-course-type", Courses__SelectCourseTypeController)

import Courses__TurnFormController from "./courses/turn_form_controller"
application.register("courses--turn-form", Courses__TurnFormController)

import Courses__TurnModalController from "./courses/turn_modal_controller"
application.register("courses--turn-modal", Courses__TurnModalController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import FormController from "./form_controller"
application.register("form", FormController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import Inscriptions__FormController from "./inscriptions/form_controller"
application.register("inscriptions--form", Inscriptions__FormController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import TselectController from "./tselect_controller"
application.register("tselect", TselectController)
