require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/company_areas", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # CompanyArea. As you add validations to CompanyArea, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CompanyArea.create! valid_attributes
      get company_areas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      company_area = CompanyArea.create! valid_attributes
      get company_area_url(company_area)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_company_area_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      company_area = CompanyArea.create! valid_attributes
      get edit_company_area_url(company_area)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CompanyArea" do
        expect {
          post company_areas_url, params: { company_area: valid_attributes }
        }.to change(CompanyArea, :count).by(1)
      end

      it "redirects to the created company_area" do
        post company_areas_url, params: { company_area: valid_attributes }
        expect(response).to redirect_to(company_area_url(CompanyArea.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CompanyArea" do
        expect {
          post company_areas_url, params: { company_area: invalid_attributes }
        }.to change(CompanyArea, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post company_areas_url, params: { company_area: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested company_area" do
        company_area = CompanyArea.create! valid_attributes
        patch company_area_url(company_area), params: { company_area: new_attributes }
        company_area.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the company_area" do
        company_area = CompanyArea.create! valid_attributes
        patch company_area_url(company_area), params: { company_area: new_attributes }
        company_area.reload
        expect(response).to redirect_to(company_area_url(company_area))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        company_area = CompanyArea.create! valid_attributes
        patch company_area_url(company_area), params: { company_area: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested company_area" do
      company_area = CompanyArea.create! valid_attributes
      expect {
        delete company_area_url(company_area)
      }.to change(CompanyArea, :count).by(-1)
    end

    it "redirects to the company_areas list" do
      company_area = CompanyArea.create! valid_attributes
      delete company_area_url(company_area)
      expect(response).to redirect_to(company_areas_url)
    end
  end
end
