require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/instructors", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Instructor. As you add validations to Instructor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Instructor.create! valid_attributes
      get instructors_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      instructor = Instructor.create! valid_attributes
      get instructor_url(instructor)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_instructor_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      instructor = Instructor.create! valid_attributes
      get edit_instructor_url(instructor)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Instructor" do
        expect {
          post instructors_url, params: { instructor: valid_attributes }
        }.to change(Instructor, :count).by(1)
      end

      it "redirects to the created instructor" do
        post instructors_url, params: { instructor: valid_attributes }
        expect(response).to redirect_to(instructor_url(Instructor.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Instructor" do
        expect {
          post instructors_url, params: { instructor: invalid_attributes }
        }.to change(Instructor, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post instructors_url, params: { instructor: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested instructor" do
        instructor = Instructor.create! valid_attributes
        patch instructor_url(instructor), params: { instructor: new_attributes }
        instructor.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the instructor" do
        instructor = Instructor.create! valid_attributes
        patch instructor_url(instructor), params: { instructor: new_attributes }
        instructor.reload
        expect(response).to redirect_to(instructor_url(instructor))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        instructor = Instructor.create! valid_attributes
        patch instructor_url(instructor), params: { instructor: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested instructor" do
      instructor = Instructor.create! valid_attributes
      expect {
        delete instructor_url(instructor)
      }.to change(Instructor, :count).by(-1)
    end

    it "redirects to the instructors list" do
      instructor = Instructor.create! valid_attributes
      delete instructor_url(instructor)
      expect(response).to redirect_to(instructors_url)
    end
  end
end
