require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/iva_conditions", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # IvaCondition. As you add validations to IvaCondition, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      IvaCondition.create! valid_attributes
      get iva_conditions_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      iva_condition = IvaCondition.create! valid_attributes
      get iva_condition_url(iva_condition)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_iva_condition_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      iva_condition = IvaCondition.create! valid_attributes
      get edit_iva_condition_url(iva_condition)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new IvaCondition" do
        expect {
          post iva_conditions_url, params: { iva_condition: valid_attributes }
        }.to change(IvaCondition, :count).by(1)
      end

      it "redirects to the created iva_condition" do
        post iva_conditions_url, params: { iva_condition: valid_attributes }
        expect(response).to redirect_to(iva_condition_url(IvaCondition.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new IvaCondition" do
        expect {
          post iva_conditions_url, params: { iva_condition: invalid_attributes }
        }.to change(IvaCondition, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post iva_conditions_url, params: { iva_condition: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested iva_condition" do
        iva_condition = IvaCondition.create! valid_attributes
        patch iva_condition_url(iva_condition), params: { iva_condition: new_attributes }
        iva_condition.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the iva_condition" do
        iva_condition = IvaCondition.create! valid_attributes
        patch iva_condition_url(iva_condition), params: { iva_condition: new_attributes }
        iva_condition.reload
        expect(response).to redirect_to(iva_condition_url(iva_condition))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        iva_condition = IvaCondition.create! valid_attributes
        patch iva_condition_url(iva_condition), params: { iva_condition: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested iva_condition" do
      iva_condition = IvaCondition.create! valid_attributes
      expect {
        delete iva_condition_url(iva_condition)
      }.to change(IvaCondition, :count).by(-1)
    end

    it "redirects to the iva_conditions list" do
      iva_condition = IvaCondition.create! valid_attributes
      delete iva_condition_url(iva_condition)
      expect(response).to redirect_to(iva_conditions_url)
    end
  end
end
