Province.create(name: 'Buenos Aires')
Province.create(name: 'Buenos Aires-GBA')
Province.create(name: 'Capital Federal')
Province.create(name: 'Catamarca')
Province.create(name: 'Chaco')
Province.create(name: 'Chubut')
Province.create(name: 'Córdoba')
Province.create(name: 'Corrientes')
Province.create(name: 'Entre Ríos')
Province.create(name: 'Formosa')
Province.create(name: 'Jujuy')
Province.create(name: 'La Pampa')
Province.create(name: 'La Rioja')
Province.create(name: 'Mendoza')
Province.create(name: 'Misiones')
Province.create(name: 'Neuquén')
Province.create(name: 'Río Negro')
Province.create(name: 'Salta')
Province.create(name: 'San Juan')
Province.create(name: 'San Luis')
Province.create(name: 'Santa Cruz')
Province.create(name: 'Santa Fe')
Province.create(name: 'Santiago del Estero')
Province.create(name: 'Tierra del Fuego')
Province.create(name: 'Tucumán')

Sector.create( name: 'Transporte' )
Sector.create( name: 'Servicios petroleros' )

IvaCondition.create( name: 'Monotributista')
IvaCondition.create( name: 'Responsable inscripto')
IvaCondition.create( name: 'Excento')